# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class LampStatus(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, is_on: bool=None):  # noqa: E501
        """LampStatus - a model defined in Swagger

        :param is_on: The is_on of this LampStatus.  # noqa: E501
        :type is_on: bool
        """
        self.swagger_types = {
            'is_on': bool
        }

        self.attribute_map = {
            'is_on': 'isOn'
        }

        self._is_on = is_on

    @classmethod
    def from_dict(cls, dikt) -> 'LampStatus':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The LampStatus of this LampStatus.  # noqa: E501
        :rtype: LampStatus
        """
        return util.deserialize_model(dikt, cls)

    @property
    def is_on(self) -> bool:
        """Gets the is_on of this LampStatus.


        :return: The is_on of this LampStatus.
        :rtype: bool
        """
        return self._is_on

    @is_on.setter
    def is_on(self, is_on: bool):
        """Sets the is_on of this LampStatus.


        :param is_on: The is_on of this LampStatus.
        :type is_on: bool
        """

        self._is_on = is_on
