# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Scheduler(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, widgets: object=None):  # noqa: E501
        """Scheduler - a model defined in Swagger

        :param widgets: The widgets of this Scheduler.  # noqa: E501
        :type widgets: object
        """
        self.swagger_types = {
            'widgets': object
        }

        self.attribute_map = {
            'widgets': 'widgets'
        }

        self._widgets = widgets

    @classmethod
    def from_dict(cls, dikt) -> 'Scheduler':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Scheduler of this Scheduler.  # noqa: E501
        :rtype: Scheduler
        """
        return util.deserialize_model(dikt, cls)

    @property
    def widgets(self) -> object:
        """Gets the widgets of this Scheduler.


        :return: The widgets of this Scheduler.
        :rtype: object
        """
        return self._widgets

    @widgets.setter
    def widgets(self, widgets: object):
        """Sets the widgets of this Scheduler.


        :param widgets: The widgets of this Scheduler.
        :type widgets: object
        """

        self._widgets = widgets
